// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-XhnkjV-_DrjGXdjqqidde-ocQMywADY',
    appId: '1:435154044067:web:759a0a27e716aa67f36b16',
    messagingSenderId: '435154044067',
    projectId: 'mrshacker-a35a6',
    authDomain: 'mrshacker-a35a6.firebaseapp.com',
    storageBucket: 'mrshacker-a35a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFueeW5j_rNUvrSIDPa_KxmxJVD_G6QgQ',
    appId: '1:435154044067:android:e8c3755a2f2757cef36b16',
    messagingSenderId: '435154044067',
    projectId: 'mrshacker-a35a6',
    storageBucket: 'mrshacker-a35a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiZw3qWwzHsaODWsGFCdIY0H3vLeLKkiA',
    appId: '1:435154044067:ios:7b8e975454b85fc8f36b16',
    messagingSenderId: '435154044067',
    projectId: 'mrshacker-a35a6',
    storageBucket: 'mrshacker-a35a6.appspot.com',
    iosBundleId: 'com.example.yusraCat03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiZw3qWwzHsaODWsGFCdIY0H3vLeLKkiA',
    appId: '1:435154044067:ios:7b8e975454b85fc8f36b16',
    messagingSenderId: '435154044067',
    projectId: 'mrshacker-a35a6',
    storageBucket: 'mrshacker-a35a6.appspot.com',
    iosBundleId: 'com.example.yusraCat03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-XhnkjV-_DrjGXdjqqidde-ocQMywADY',
    appId: '1:435154044067:web:d9713bde9a8925c1f36b16',
    messagingSenderId: '435154044067',
    projectId: 'mrshacker-a35a6',
    authDomain: 'mrshacker-a35a6.firebaseapp.com',
    storageBucket: 'mrshacker-a35a6.appspot.com',
  );
}
